### ISSUE TITLE
executing dependency plugin list goal is not working

### ISSUE THREAD

**Issue by kamaltherocky** [mojo-executor/mojo-executor#3]
Hi

I was trying to execute the dependency plugin through the mojo executor. The weird thing is "tree" goal is working and generating the file with the dependency tree information. But when i change the goal to "list" or "copy-dependencies", the execution goes through fine but no action happens. There is no error or warning. when i enable debug messages, i see that the execution of plugin stops during configuration.

Regards
Kamal

**Comment by rsercano** [comment]
Very good explanation @nfleury thanks a lot !
