### ISSUE TITLE
Move to an organization?

### ISSUE THREAD

**Issue by TimMoore** [mojo-executor/mojo-executor#63]
GitHub offers more flexible access control for repositories owned by organizations vs. individual accounts. See [Permission levels for a user account repository](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/permission-levels-for-a-user-account-repository).

I've thought about transferring this project to an organization. There's no reason to keep it associated with my personal account, since I am neither the original creator nor the most active maintainer (or even a user at this point).

Is there an existing organization that would make sense as a home for the project, or should I create a dedicated one?

I'm opening this for public discussion for 14 days.

@rnc: since you have done all of the recent maintenance, I won't make any changes unless you agree.

I'd be happy to hear from any other users, former maintainers, or other interested people as well. If there aren't any objections or suitable existing organizations suggested by 20 Sep 2021, I'll plan to transfer the repository to the https://github.com/mojo-executor organization, which I have just reserved. If we do find a more suitable organization, I'll delete that one.

**Comment by rnc** [comment]
I'm fine with this ; seems like a good idea to me!

**Comment by TimMoore** [comment]
I've done the transfer.
