### ISSUE TITLE
Try moving dependencies to the provided scope

### ISSUE THREAD

**Issue by TimMoore** [mojo-executor/mojo-executor#69]
Security scanners often report vulnerabilities in dependencies used by Mojo Executor.

For example:

https://sbom.lift.sonatype.com/report/T1-0ff0976f7f21c391f20f-33e73166f180ff-1644469806-424d7caf0d4044f58b407ae6c76e3af8

Mojo Executor is really only intended to run inside a Maven plugin. I believe that all of its dependencies ought to be provided by Maven itself, so they should be in the `provided` scope rather than `compile`.

**Comment by kwin** [comment]
To prevent unnecessary artifact downloads with Maven 3 all dependencies provided by the Maven distribution should have scope "provided" (and only be listed with the version shipping with the minimum Maven version being supported). For further info look at https://issues.apache.org/jira/browse/MPLUGIN-370 and https://issues.apache.org/jira/browse/MNG-7097.
This only includes those dependencies managed by Maven, see https://maven.apache.org/guides/mini/guide-maven-classloading.html#2-core-classloader but not the other ones potentially used by other plugins. Each plugin manages its needed version by itself, as each plugin classloader is isolated: https://maven.apache.org/guides/mini/guide-maven-classloading.html#3-plugin-classloaders

**Comment by TimMoore** [comment]
Thanks, @kwin. Makes perfect sense. Would you be willing to send a pull request to update the scope where applicable?

**Comment by kwin** [comment]
@TimMoore Would it be possible to spin a release with these changes soon?

**Comment by TimMoore** [comment]
@kwin sorry for the delay. Version 2.4.0 is now available in central. Thanks again!

Would you like to be acknowledged in the contributor list in the README and `pom.xml`?

**Comment by kwin** [comment]
@TimMoore Thanks a lot. No need to mention me in readme nor pom.xml.
