### ISSUE TITLE
Update release configuration to current recommendations

### ISSUE THREAD

**Issue by TimMoore** [mojo-executor/mojo-executor#70]
Sonatype's [instructions for releasing Maven projects](https://central.sonatype.org/publish/publish-maven/) have changed since this project was configured to do so.

In particular:

- The [`oss-parent`](https://central.sonatype.org/publish/publish-maven/#deprecated-oss-parent) POM is deprecated
- They recommend use of the [Nexus Staging Maven Plugin](https://central.sonatype.org/publish/publish-maven/#nexus-staging-maven-plugin-for-deployment-and-release)

**Comment by cowwoc** [comment]
I'm so happy you linked to this documentation. I had no idea that `oss-parent` was deprecated nor that the documentation at https://central.sonatype.org/publish/publish-maven/ even existed. I guess it's time to update all my projects.

PS: A new version of the staging plugin just came out. Be sure to update to it to avoid a host of bugs and vulnerabilities. See https://github.com/sonatype/nexus-maven-plugins/pull/91

**Comment by TimMoore** [comment]
Yeah, I just went digging up that documentation because I had honestly forgotten how to release to the OSSRH server.
