### ISSUE TITLE
Rename the default branch from 'master' to 'main'

### ISSUE THREAD

**Issue by TimMoore** [mojo-executor/mojo-executor#72]
GitHub has [made this really easy now](https://github.com/github/renaming).

**Comment by rnc** [comment]
We've done this for many of our repositories and I agree its trivially easy to do.

**Comment by TimMoore** [comment]
This is done now.

Local clones can be updated with these commands:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by TimMoore** [comment]
I think this broke the GitHub Actions workflow... I'll have a look.
